#include <pmdsky.h>
#include <cot.h>
#include "extern.h"

/*
  Returns the highest level across the current active team. If no valid team members are found, the max returned is 0.
*/
uint8_t GetHighestLevelTeamMember(void) {
    uint8_t max = 0;
    for(int i = 0; i < 4; i++) {
        struct team_member* member = GetActiveTeamMember(i);
        if(member != NULL && member->f_is_valid && member->level > max)
            max = member->level;
    }
    return max;
}

/*
  Determines how to initialize a ground monster that has its data stem from a guest monster.
  If a condition is met, then the ground monster will become the level of the highest team member and have its stats and moves adjusted accordingly.
  A moveset is generated by taking only the first four possible moves from a monster's level up learnset.

  TODO: Use a proper condition for the check and possibly rethink how moves are generated.
*/
__attribute((used)) void CustomGuestMonsterToGroundMonster(struct ground_monster* ground_monster, struct guest_monster* guest_monster) {
    if(false) { // TODO: Replace with an actual condition
        ground_monster->is_valid = true;
        ground_monster->id = guest_monster->id;
        ground_monster->tactic.val = TACTIC_LETS_GO_TOGETHER;
        ground_monster->joined_at = guest_monster->joined_at;
        ground_monster->joined_at = guest_monster->joined_at;
        ground_monster->joined_at_floor = guest_monster->joined_at_floor;
        ground_monster->level_at_first_evo = 0;
        ground_monster->level_at_second_evo = 0;
        SetBaseStatsMovesGroundMonster(ground_monster);
        ground_monster->iq = guest_monster->iq;
        ApplyLevelUpBoostsToGroundMonster(ground_monster, GetHighestLevelTeamMember(), false);
        EnableAllLearnableIqSkills(ground_monster->iq_skill_flags, ground_monster->id.val, ground_monster->iq);
        StrncpySimple(ground_monster->name, guest_monster->name, 10);
    }
    else
        GuestMonsterToGroundMonster(ground_monster, guest_monster);
}
